type: object

x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1

  publishedVersion: "1.0.0"
  publishedVersionMetadata:
    releaseNote: >-
      Initial Marketplace release for Glassbox Bio Molecular Audit.
    releaseTypes:
      - Feature
    recommended: true

  deployment:
    chart:
      name: molecular-audit-core

  images:
    "":
      properties:
        imageRepo:
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG
    console:
      properties:
        consoleImageRepo:
          type: REPO_WITH_REGISTRY
        consoleImageTag:
          type: TAG
    ubbagent:
      properties:
        ubbagentImageRepo:
          type: REPO_WITH_REGISTRY
        ubbagentImageTag:
          type: TAG

  configurableResources:
    - name: molecular-audit-core
      values:
        # NAME/NAMESPACE fields control the Helm release name and namespace.
        job.enabled: false
        console.enabled: true

        marketplace.reportingSecret: $reportingSecret
        ubbagent.enabled: true
        ubbagent.serviceName: "services/REPLACE_ME_SERVICE_NAME"
        ubbagent.metricName: glassbox_mol_audit_run
        ubbagent.localPort: "4567"
        ubbagent.image.repository: $ubbagentImageRepo
        ubbagent.image.tag: $ubbagentImageTag

        image.repository: $imageRepo
        image.tag: $imageTag
        console.image.repository: $consoleImageRepo
        console.image.tag: $consoleImageTag

        config.projectId: $projectId
        config.phase: $phase
        config.novelTargetMode: $novelTargetMode
        config.triangulationRequired: $triangulationRequired
        config.verdictMode: $verdictMode
        config.rubricPreset: $rubricPreset
        config.failClosed: $failClosed
        config.reproPackEnabled: $reproPackEnabled
        config.standardModeQuiet: $standardModeQuiet

        storage.type: $storageType
        storage.pvc.size: $pvcSize
        storage.pvc.storageClassName: $pvcStorageClass
        storage.gcs.bucket: $gcsBucket

        workloadIdentity.enabled: $workloadIdentityEnabled
        workloadIdentity.gcpServiceAccount: $gcpServiceAccount

properties:
  name:
    type: string
    title: Application name
    x-google-marketplace:
      type: NAME

  namespace:
    type: string
    title: Kubernetes namespace
    x-google-marketplace:
      type: NAMESPACE

  reportingSecret:
    type: string
    title: Marketplace reporting secret
    description: Kubernetes Secret name injected by Marketplace for usage reporting.
    x-google-marketplace:
      type: REPORTING_SECRET

  projectId:
    type: string
    title: Project ID
    default: mol_audit_demo

  phase:
    type: string
    title: Mode
    default: Glassbox Bio Molecular Audit

  novelTargetMode:
    type: boolean
    title: Novel target audit mode
    default: false

  triangulationRequired:
    type: boolean
    title: Require convergent evidence
    default: true

  verdictMode:
    type: string
    title: Verdict framing
    enum:
      - verdict_as_risk
      - verdict_as_truth
    default: verdict_as_risk

  rubricPreset:
    type: string
    title: Success rubric preset
    enum:
      - vc_diligence
      - early_discovery
      - covalent
      - senolytic
    default: vc_diligence

  failClosed:
    type: boolean
    title: Fail closed on inadmissible inputs
    default: true

  reproPackEnabled:
    type: boolean
    title: Include Repro Pack outputs
    default: true

  standardModeQuiet:
    type: boolean
    title: Suppress standard-mode skip warnings
    default: false

  storageType:
    type: string
    title: Storage type
    enum:
      - pvc
      - gcs
    default: pvc

  pvcSize:
    type: string
    title: PVC size
    default: 50Gi

  pvcStorageClass:
    type: string
    title: PVC StorageClass
    default: standard

  gcsBucket:
    type: string
    title: GCS bucket (for gcs storage)
    default: ""

  workloadIdentityEnabled:
    type: boolean
    title: Enable Workload Identity (GCS mode)
    default: false

  gcpServiceAccount:
    type: string
    title: GCP Service Account (Workload Identity)
    default: ""

required:
  - name
  - namespace
  - reportingSecret
